// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syhntyfwecsjbufavede.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5aG50eWZ3ZWNzamJ1ZmF2ZWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3MTAwNzEsImV4cCI6MjA3NjI4NjA3MX0.6LdPTTFpLR5vtYxfUZ4sIIi6HPhJqSktTCEVGcFZaoo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});